routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PagesAdminController;
use App\Http\Controllers\ChaineController;
use App\Http\Controllers\CheickController;
use App\Http\Controllers\LangueController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\NiveauController;
use App\Http\Controllers\DourousController;
use App\Http\Controllers\DarsController;


// Route::get('/', ['as'=>'root_index', 'uses'=>'PagesController@index']);

Route::get('/', [PagesController::class, 'index'])->name('root_index');
Route::get('/dourous', [PagesController::class, 'dourous'])->name('dourous');
Route::get('/dars/{slug_dars}', [PagesController::class, 'dars'])->name('dars');
Route::get('/categorie/{slug_categorie}', [PagesController::class, 'categorie_dourous'])->name('categorie_dourous');
Route::get('/coran', [PagesController::class, 'coran'])->name('coran');
Route::get('/conferences', [PagesController::class, 'conferences'])->name('conferences');


Route::group(['prefix' => 'dashboard','middleware' => ['auth']], function () {
    Route::get('/index', [PagesAdminController::class, 'index'])->name('dashboard.index');
    Route::resource('chaine', ChaineController::class);
    Route::resource('cheick', CheickController::class);
    Route::resource('langue', LangueController::class);
    Route::resource('categorie', CategorieController::class);
    Route::resource('niveau', NiveauController::class);
    Route::resource('dourous', DourousController::class);
    Route::resource('{slug}/dars', DarsController::class);

    
});

app/Models/Cheick.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cheick extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
}

app/Http/Controllers/CheickController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Cheick;
use Auth;
use Str;
class CheickController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $cheicks = Cheick::all();
        return view('backoffice.cheicks.index',compact('cheicks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backoffice.cheicks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $cheick = new Cheick();
        $cheick->nom = $request->nom;
        $cheick->prenom = $request->prenom;
        $cheick->telephone = $request->telephone;
        $cheick->fonction = $request->fonction;
        $cheick->kouniah = $request->kouniah;
        $cheick->email = $request->email;
        $cheick->parcours = $request->parcours;
        $cheick->save();
        return redirect(route('cheick.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cheick = Cheick::find($id);
        return view('backoffice.cheicks.edit',compact('cheick'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backoffice/cheicks/create.blade.php
@extends('backoffice.layouts.app')
@section('content')
<div class="page-content-wrapper">
				<div class="page-content">
					<div class="page-bar">
						<div class="page-title-breadcrumb">
							<div class=" pull-left">
								<div class="page-title">Ajouter un cheick</div>
							</div>
							<ol class="breadcrumb page-breadcrumb pull-right">
								<li><i class="fa fa-home"></i>&nbsp;<a class="parent-item"
										href="{{route('dashboard.index')}}">Accueil</a>&nbsp;<i class="fa fa-angle-right"></i>
								</li>
								<li class="active">Ajouter un cheick</li>
							</ol>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<div class="card-box">
								<div class="card-head">
									<header class="text-center">Ajouter un cheick</header>
								</div>
								<div class="card-body">
									<form action="{{route('cheick.store')}}" method="POST">
                                        @csrf
                                       <div class="row">
                                            <div class="offset-lg-1 col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Nom du cheick</label>
                                                    <input type="text" class="form-control" id="simpleFormEmail" name="nom" placeholder="Nom du cheick">
                                                </div>
                                            </div>
                                            <div class="col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Prénom du cheick</label>
                                                    <input type="text" class="form-control" id="simpleFormEmail" name="prenom" placeholder="Prénom du cheick">
                                                </div>
                                            </div>
                                       </div>
                                       <div class="row">
                                            <div class="offset-lg-1 col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Téléphone du cheick</label>
                                                    <input type="tel" class="form-control" id="simpleFormEmail" name="telephone" placeholder="Téléphone">
                                                </div>
                                            </div>
                                            <div class="col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">kouniah du cheick</label>
                                                    <input type="text" class="form-control" id="simpleFormEmail" name="kouniah" placeholder="Adresse E-mail">
                                                </div>
                                            </div>
                                       </div>
                                       <div class="row">
                                            <div class="offset-lg-1 col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Fonction </label>
                                                    <input type="text" class="form-control" id="simpleFormEmail" name="fonction" placeholder="Fonction">
                                                </div>
                                            </div>
                                            <div class="col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Adresse E-mail du cheick</label>
                                                    <input type="email" class="form-control" id="simpleFormEmail" name="email" placeholder="Adresse E-mail">
                                                </div>
                                            </div>
                                       </div>
                                       <div class="row">
                                        <div class="offset-lg-1 col-lg-10 p-t-20">
                                                <textarea name="formsummernote" name="parcours" id="formsummernote" cols="15" rows="5">

                                                </textarea>
                                            </div>
                                       </div>
                                    
                                        <div class="col-lg-12 p-t-20 text-center">
                                            <button type="submit"
                                                class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 btn-pink">Enregister</button>
                                            <button type="button"
                                                class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 btn-default">Fermer</button>
                                        </div>
                                    </form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
@endsection

resources/views/backoffice/cheicks/edit.blade.php
@extends('backoffice.layouts.app')
@section('content')
<div class="page-content-wrapper">
				<div class="page-content">
					<div class="page-bar">
						<div class="page-title-breadcrumb">
							<div class=" pull-left">
								<div class="page-title">Modification d'une chaine</div>
							</div>
							<ol class="breadcrumb page-breadcrumb pull-right">
								<li><i class="fa fa-home"></i>&nbsp;<a class="parent-item"
										href="{{route('dashboard.index')}}">Accueil</a>&nbsp;<i class="fa fa-angle-right"></i>
								</li>
								<li class="active">Modification d'une chaine</li>
							</ol>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<div class="card-box">
								<div class="card-head">
									<header class="text-center">Modification d'une chaine</header>
								</div>
								<div class="card-body">
									<form action="{{route('chaine.update',$chaine->id)}}" method="POST" enctype="multipart/form-data">
                                    @method('PUT')  
                                    @csrf
                                       <div class="row">
                                            <div class="offset-lg-1 col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Nom de la chaine</label>
                                                    <input type="text" class="form-control" id="simpleFormEmail" value="{{ $chaine->libelle }}" name="name" placeholder="Nom de la chaine">
                                                </div>
                                            </div>
                                            <div class="col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Logo</label>
                                                    <input type="file" class="form-control" id="simpleFormEmail" value="{{ $chaine->photo }}" name="logo"  placeholder="logo">
                                                </div>
                                            </div>
                                       </div>
                                       <div class="row">
                                            <div class="offset-lg-1 col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Téléphone</label>
                                                    <input type="tel" class="form-control" id="simpleFormEmail" value="{{ $chaine->telephone }}" name="telephone" placeholder="Téléphone">
                                                </div>
                                            </div>
                                            <div class="col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Adresse E-mail</label>
                                                    <input type="email" class="form-control" id="simpleFormEmail" value="{{ $chaine->email }}" name="email" placeholder="Adresse E-mail">
                                                </div>
                                            </div>
                                       </div>
                                    
                                        <div class="col-lg-12 p-t-20 text-center">
                                            <button type="submit"
                                                class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 btn-pink">Enregister</button>
                                            <button type="button"
                                                class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 btn-default">Fermer</button>
                                        </div>
                                    </form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
@endsection

resources/views/backoffice/cheicks/index.blade.php
@extends('backoffice.layouts.app')
@section('content')
<div class="page-content-wrapper">
				<div class="page-content">
					<div class="page-bar">
						<div class="page-title-breadcrumb">
							<div class=" pull-left">
								<div class="page-title">Liste des cheicks</div>
							</div>
							<ol class="breadcrumb page-breadcrumb pull-right">
								<li><i class="fa fa-home"></i>&nbsp;<a class="parent-item"
										href="">Accueil</a>&nbsp;<i class="fa fa-angle-right"></i>
								</li>
								<li class="active">Liste des cheicks</li>
							</ol>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12 col-md-12 col-xl-12">
							<div class="card-box">
								<div class="card-head">
									<header>Liste des cheicks</header>
								</div>
								<div class="card-body ">
									<!-- <div class="row">
										<div class="col-md-6 col-sm-6 col-6">
											<div class="btn-group">
												<a href="{{route('cheick.create')}}" id="addRow" class="btn btn-info">
													Ajouter un nouveau cheick <i class="fa fa-plus"></i>
												</a>
											</div>
										</div>
                                    </div> -->
                                    <div class="row">
                                    @forelse($cheicks as $cheick)
                                        <div class="col-md-6">
                                            <div class="card">
                                                <div class="card-body no-padding height-9">
                                                    <div class="row">
                                                        <div class="profile-userpic">
                                                                <img src="/backoffice/assets/img/avatar.png" class="img-responsive" alt=""> </div>
                                                        </div>
                                                    <div class="profile-usertitle">
                                                        <div class="profile-usertitle-name"> {{$cheick->nom}} {{$cheick->prenom}} </div>
                                                        <div class="profile-usertitle-job"> {{$cheick->kouniah}} </div>
                                                    </div>
                                                    <div class="profile-desc">
                                                        {{$cheick->parcours}} 
                                                    </div>
                                                    <ul class="list-group list-group-unbordered">
                                                        <li class="list-group-item">
                                                            <b>Téléphone </b>
                                                            <div class="profile-desc-item pull-right">{{$cheick->telephone}} </div>
                                                        </li>
                                                        <li class="list-group-item">
                                                            <b>Adresse E-mail </b>
                                                            <div class="profile-desc-item pull-right">{{$cheick->email}}</div>
                                                        </li>
                                                        <li class="list-group-item">
                                                            <b>Fonction </b>
                                                            <div class="profile-desc-item pull-right">{{$cheick->fonction}}</div>
                                                        </li>
                                                    </ul>
                                                    <div class="row list-separated profile-stat">
                                                        <div class="col-md-6 col-sm-4 col-6">
                                                            <div class="uppercase profile-stat-title"> 37 </div>
                                                            <div class="uppercase profile-stat-text"> Cours donnés </div>
                                                        </div>
                                                        <div class="col-md-6 col-sm-4 col-6">
                                                            <div class="uppercase profile-stat-title"> 151 </div>
                                                            <div class="uppercase profile-stat-text"> Etudiants </div>
                                                        </div>

                                                    </div>
                                                    <div class="profile-userbuttons">
                                                        <button type="button"
                                                                class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 btn-circle btn-success">Modifier</button>
                                                        <button type="button"
                                                                class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 btn-circle btn-info">Voir ses dourous</button>
                                                                <button type="button"
                                                                class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 btn-circle btn-danger">Bloquer ce cheick</button>
										             </div>
                                                </div>
                                    </div>

                                    </div>
                                    @empty
                                     @endforelse
                                    </div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
@endsection