routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PagesAdminController;
use App\Http\Controllers\ChaineController;
use App\Http\Controllers\CheickController;
use App\Http\Controllers\LangueController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\NiveauController;
use App\Http\Controllers\DourousController;
use App\Http\Controllers\DarsController;


// Route::get('/', ['as'=>'root_index', 'uses'=>'PagesController@index']);

Route::get('/', [PagesController::class, 'index'])->name('root_index');
Route::get('/dourous', [PagesController::class, 'dourous'])->name('dourous');
Route::get('/dars/{slug_dars}', [PagesController::class, 'dars'])->name('dars');
Route::get('/categorie/{slug_categorie}', [PagesController::class, 'categorie_dourous'])->name('categorie_dourous');
Route::get('/coran', [PagesController::class, 'coran'])->name('coran');
Route::get('/conferences', [PagesController::class, 'conferences'])->name('conferences');


Route::group(['prefix' => 'dashboard','middleware' => ['auth']], function () {
    Route::get('/index', [PagesAdminController::class, 'index'])->name('dashboard.index');
    Route::resource('chaine', ChaineController::class);
    Route::resource('cheick', CheickController::class);
    Route::resource('langue', LangueController::class);
    Route::resource('categorie', CategorieController::class);
    Route::resource('niveau', NiveauController::class);
    Route::resource('dourous', DourousController::class);
    Route::resource('{slug}/dars', DarsController::class);

    
});

app/Models/Langue.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Langue extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

}

app/Http/Controllers/LangueController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Langue;
use Str;

class LangueController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $langues = Langue::all();
        return view('backoffice.admin.langues.index',compact('langues'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('backoffice.admin.langues.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $langue = new Langue();
        $langue->libelle = $request->libelle;
        $langue->slug_langue= Str::slug($request->libelle,'-');
        $langue->save();
        return redirect(route('langue.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backoffice/admin/langues/create.blade.php
@extends('backoffice.layouts.app')
@section('content')
<div class="page-content-wrapper">
				<div class="page-content">
					<div class="page-bar">
						<div class="page-title-breadcrumb">
							<div class=" pull-left">
								<div class="page-title">Ajouter une langue</div>
							</div>
							<ol class="breadcrumb page-breadcrumb pull-right">
								<li><i class="fa fa-home"></i>&nbsp;<a class="parent-item"
										href="{{route('dashboard.index')}}">Accueil</a>&nbsp;<i class="fa fa-angle-right"></i>
								</li>
								<li class="active">Ajouter une langue</li>
							</ol>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<div class="card-box">
								<div class="card-head">
									<header class="text-center">Ajouter une langue</header>
								</div>
								<div class="card-body">
									<form action="{{route('langue.store')}}" method="POST">
                                        @csrf
                                       <div class="row">
                                            <div class="offset-lg-3 col-lg-6 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Le libelle de la langue</label>
                                                    <input type="text" class="form-control" id="simpleFormEmail" name="libelle" placeholder="Le libelle de la langue">
                                                </div>
                                            </div>

                                       </div>
                                    
                                        <div class="col-lg-12 p-t-20 text-center">
                                            <button type="submit"
                                                class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 btn-pink">Enregister</button>
                                            <button type="button"
                                                class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 btn-default">Fermer</button>
                                        </div>
                                    </form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
@endsection

resources/views/backoffice/admin/langues/index.blade.php
@extends('backoffice.layouts.app')
@section('content')
<div class="page-content-wrapper">
				<div class="page-content">
					<div class="page-bar">
						<div class="page-title-breadcrumb">
							<div class=" pull-left">
								<div class="page-title">Langue</div>
							</div>
							<ol class="breadcrumb page-breadcrumb pull-right">
								<li><i class="fa fa-home"></i>&nbsp;<a class="parent-item"
										href="index.html">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
								</li>
								<li class="active">Liste des langues</li>
							</ol>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12 col-md-12 col-xl-12">
							<div class="card-box">
								<div class="card-body ">
                                <div class="row">
								    <div class="col-md-6 col-sm-6 col-6">
										<div class="btn-group">
												<a href="{{route('langue.create')}}" id="addRow" class="btn btn-info">
													Ajouter une langue <i class="fa fa-plus"></i>
												</a>
										</div>
									</div>
								</div>
									<div class="table-scrollable">
										<table
											class="table table-striped table-bordered table-hover table-checkable order-column valign-middle"
											id="example4">
											<thead>
												<tr>
													<th>#</th>
													<th class="text-center">Libelle de la langue</th>
													<th class="text-center">Action</th>
												</tr>
											</thead>
											<tbody>
											@forelse($langues as $langue)
                                            <tr class="even">
													<td>{{$langue->id}}</td>
													<td class="text-center">{{$langue->libelle}}</td>
													<td class="text-center"><a href="javascript:void(0)" class="" data-toggle="tooltip"
															title="Edit">
                                                            <i class="fa fa-check"></i></a> 
                                                            <a href="javascript:void(0)"
															class="text-inverse" title="Delete" data-toggle="tooltip">
															<i class="fa fa-trash text-danger"></i></a>
													</td>
												</tr>
                                            @empty
                                            @endforelse
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
@endsection