routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PagesAdminController;
use App\Http\Controllers\ChaineController;
use App\Http\Controllers\CheickController;
use App\Http\Controllers\LangueController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\NiveauController;
use App\Http\Controllers\DourousController;
use App\Http\Controllers\DarsController;


// Route::get('/', ['as'=>'root_index', 'uses'=>'PagesController@index']);

Route::get('/', [PagesController::class, 'index'])->name('root_index');
Route::get('/dourous', [PagesController::class, 'dourous'])->name('dourous');
Route::get('/dars/{slug_dars}', [PagesController::class, 'dars'])->name('dars');
Route::get('/categorie/{slug_categorie}', [PagesController::class, 'categorie_dourous'])->name('categorie_dourous');
Route::get('/coran', [PagesController::class, 'coran'])->name('coran');
Route::get('/conferences', [PagesController::class, 'conferences'])->name('conferences');


Route::group(['prefix' => 'dashboard','middleware' => ['auth']], function () {
    Route::get('/index', [PagesAdminController::class, 'index'])->name('dashboard.index');
    Route::resource('chaine', ChaineController::class);
    Route::resource('cheick', CheickController::class);
    Route::resource('langue', LangueController::class);
    Route::resource('categorie', CategorieController::class);
    Route::resource('niveau', NiveauController::class);
    Route::resource('dourous', DourousController::class);
    Route::resource('{slug}/dars', DarsController::class);

    
});

app/Models/Chaine.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Chaine extends Model
{
    use HasFactory;

    const ACTIF = 'actif';
    const PASSIF = 'passif';
    const STATUT = [Chaine::ACTIF, Chaine::PASSIF];

    protected $guarded = ['id'];

    public function user(){return $this->belongsTo('App\Models\User', 'created_by');}
}

app/Http/Controllers/ChaineController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Chaine;
use App\Models\ChaineUser;
use Auth;
use Str;
class ChaineController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $chaines = Chaine::all();
        return view('backoffice.chaines.index',compact('chaines'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backoffice.chaines.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->file('logo'));
        if ($request->file('logo')) {
            $image = $request->file('logo');
            $link = Str::slug($request->name).'.'.$image->extension();
            $image->move('uploads/chaine/', $link);
            $link = '/uploads/chaine/'.$link;
        } else {
            $link ='/defaultImages/chaine.png';
        }

        $user = Auth::user();

        $chaine = new Chaine();
        $chaine->libelle = $request->name;
        $chaine->email = $request->email;
        $chaine->telephone = $request->telephone;
        $chaine->adresse = $request->adresse;
        $chaine->logo = $link;
        $chaine->statut = Chaine::ACTIF;
        $chaine->created_by = $user->id;
        $chaine->slug = Str::slug($request->name,'-');

        if ($chaine->save()) {

            // flashy()->info('Votre chaine a été crée avec succèss');
            ChaineUser::create([
                'chaine_id' => $chaine->id,
                'user_id' => $user->id
                // 'type' => 'owner'
            ]);
            $user->type = 'organisateur';
            $user->save();
            
            return redirect(route('chaine.index'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $chaine = Chaine::find($id);
        return view('backoffice.chaines.edit',compact('chaine'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        if ($request->file('logo')) {
            $image = $request->file('logo');
            $link = Str::slug($request->name).'.'.$image->extension();
            $image->move('uploads/chaine/', $link);
            $link = '/uploads/chaine/'.$link;
        } else {
            $link ='/defaultImages/chaine.png';
        }
        
        $chaine = Chaine::find($id);
        $chaine->libelle = $request->name;
        $chaine->email = $request->email;
        $chaine->telephone = $request->telephone;
        $chaine->adresse = $request->adresse;
        $chaine->logo = $link;
        $chaine->statut = Chaine::ACTIF;
        $chaine->slug = Str::slug($request->name,'-');
        $chaine->save();
        return redirect(route('chaine.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backoffice/chaines/create.blade.php
@extends('backoffice.layouts.app')
@section('content')
<div class="page-content-wrapper">
				<div class="page-content">
					<div class="page-bar">
						<div class="page-title-breadcrumb">
							<div class=" pull-left">
								<div class="page-title">Ajouter une chaine</div>
							</div>
							<ol class="breadcrumb page-breadcrumb pull-right">
								<li><i class="fa fa-home"></i>&nbsp;<a class="parent-item"
										href="{{route('dashboard.index')}}">Accueil</a>&nbsp;<i class="fa fa-angle-right"></i>
								</li>
								<li class="active">Ajouter une chaine</li>
							</ol>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<div class="card-box">
								<div class="card-head">
									<header class="text-center">Ajouter une chaine</header>
								</div>
								<div class="card-body">
									<form action="{{route('chaine.store')}}" method="POST" enctype="multipart/form-data">
                                        @csrf
                                       <div class="row">
                                            <div class="offset-lg-1 col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Nom de la chaine</label>
                                                    <input type="text" class="form-control" id="simpleFormEmail" name="name" placeholder="Nom de la chaine">
                                                </div>
                                            </div>
                                            <div class="col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Logo</label>
                                                    <input type="file" class="form-control" id="simpleFormEmail" name="logo" placeholder="logo">
                                                </div>
                                            </div>
                                       </div>
                                       <div class="row">
                                            <div class="offset-lg-1 col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Téléphone</label>
                                                    <input type="tel" class="form-control" id="simpleFormEmail" name="telephone" placeholder="Téléphone">
                                                </div>
                                            </div>
                                            <div class="col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Adresse E-mail</label>
                                                    <input type="email" class="form-control" id="simpleFormEmail" name="email" placeholder="Adresse E-mail">
                                                </div>
                                            </div>
                                       </div>
                                    
                                        <div class="col-lg-12 p-t-20 text-center">
                                            <button type="submit"
                                                class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 btn-pink">Enregister</button>
                                            <button type="button"
                                                class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 btn-default">Fermer</button>
                                        </div>
                                    </form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
@endsection

resources/views/backoffice/chaines/edit.blade.php
@extends('backoffice.layouts.app')
@section('content')
<div class="page-content-wrapper">
				<div class="page-content">
					<div class="page-bar">
						<div class="page-title-breadcrumb">
							<div class=" pull-left">
								<div class="page-title">Modification d'une chaine</div>
							</div>
							<ol class="breadcrumb page-breadcrumb pull-right">
								<li><i class="fa fa-home"></i>&nbsp;<a class="parent-item"
										href="{{route('dashboard.index')}}">Accueil</a>&nbsp;<i class="fa fa-angle-right"></i>
								</li>
								<li class="active">Modification d'une chaine</li>
							</ol>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<div class="card-box">
								<div class="card-head">
									<header class="text-center">Modification d'une chaine</header>
								</div>
								<div class="card-body">
									<form action="{{route('chaine.update',$chaine->id)}}" method="POST" enctype="multipart/form-data">
                                    @method('PUT')  
                                    @csrf
                                       <div class="row">
                                            <div class="offset-lg-1 col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Nom de la chaine</label>
                                                    <input type="text" class="form-control" id="simpleFormEmail" value="{{ $chaine->libelle }}" name="name" placeholder="Nom de la chaine">
                                                </div>
                                            </div>
                                            <div class="col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Logo</label>
                                                    <input type="file" class="form-control" id="simpleFormEmail" value="{{ $chaine->photo }}" name="logo"  placeholder="logo">
                                                </div>
                                            </div>
                                       </div>
                                       <div class="row">
                                            <div class="offset-lg-1 col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Téléphone</label>
                                                    <input type="tel" class="form-control" id="simpleFormEmail" value="{{ $chaine->telephone }}" name="telephone" placeholder="Téléphone">
                                                </div>
                                            </div>
                                            <div class="col-lg-5 p-t-20">
                                                <div class="form-group">
                                                    <label for="simpleFormEmail">Adresse E-mail</label>
                                                    <input type="email" class="form-control" id="simpleFormEmail" value="{{ $chaine->email }}" name="email" placeholder="Adresse E-mail">
                                                </div>
                                            </div>
                                       </div>
                                    
                                        <div class="col-lg-12 p-t-20 text-center">
                                            <button type="submit"
                                                class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 btn-pink">Enregister</button>
                                            <button type="button"
                                                class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 btn-default">Fermer</button>
                                        </div>
                                    </form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
@endsection

resources/views/backoffice/chaines/index.blade.php
@extends('backoffice.layouts.app')
@section('content')
<div class="page-content-wrapper">
				<div class="page-content">
					<div class="page-bar">
						<div class="page-title-breadcrumb">
							<div class=" pull-left">
								<div class="page-title">Liste des chaines</div>
							</div>
							<ol class="breadcrumb page-breadcrumb pull-right">
								<li><i class="fa fa-home"></i>&nbsp;<a class="parent-item"
										href="">Accueil</a>&nbsp;<i class="fa fa-angle-right"></i>
								</li>
								<li class="active">Liste des chaines</li>
							</ol>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12 col-md-12 col-xl-12">
							<div class="card-box">
								<div class="card-head">
									<header>Liste des chaines</header>
								</div>
								<div class="card-body ">
									<div class="row">
										<div class="col-md-6 col-sm-6 col-6">
											<div class="btn-group">
												<a href="{{route('chaine.create')}}" id="addRow" class="btn btn-info">
													Ajouter une nouvelle chaine <i class="fa fa-plus"></i>
												</a>
											</div>
										</div>
                                    </div>
                                    <div class="row">
                                    @forelse($chaines as $chaine)
                                        <div class="col-md-4">
                                            <div class="profile-sidebar">
                                                <div class="card card-topline-aqua">
                                                    <div class="card-head card-topline-aqua">
                                                        <header class="text-center">{{$chaine->libelle}}</header>
                                                    </div>
                                                    <div class="card-body no-padding height-9">
                                                        <div class="row">
                                                            <!-- <div class="profile-usertitle text-center">
                                                                <div class="profile-usertitle-name"> {{$chaine->libelle}} </div>
                                                            </div> -->
                                                            <div class="course-picture">
                                                                <img src="{{$chaine->logo}}"  style="height:100px" class="ml-5 img-responsive"
                                                                    alt=""> 
                                                            </div>
                                                        </div>
                                                        <ul class="list-group list-group-unbordered">
                                                            <li class="list-group-item">
                                                                <b>Téléphone </b>
                                                                <div class="profile-desc-item pull-right">{{$chaine->telephone}}</div>
                                                            </li>
                                                            <li class="list-group-item">
                                                                <b>Adresse E-mail </b>
                                                                <div class="profile-desc-item pull-right">{{ $chaine->email}}</div>
                                                            </li>
                                                            <li class="list-group-item">
                                                                <b>Propriétaire</b>
                                                                <div class="profile-desc-item pull-right">{{ $chaine->user->full_name()}}</div>
                                                            </li>
                                                            <li class="list-group-item">
                                                                <b>Date de création</b>
                                                                <div class="profile-desc-item pull-right">{{ date('d/m/Y', strtotime($chaine->created_at))}}</div>
                                                            </li>
										                </ul>
                                                        <!-- END SIDEBAR USER TITLE -->
                                                        <div class="col-lg-12 p-t-20 text-center">
                                                                <a href="{{route('chaine.edit',$chaine->id)}}"
                                                                    class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 btn-success">Modifier</a>
                                                                <a href="" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 btn-danger">Supprimer</a>
                                                        </div>
                                                    </div>
                                                </div>
                                    
                                            </div>
                                        </div>
                                    @empty
                                     @endforelse
                                    </div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
@endsection